# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPrk1KdBeBHTcVmVRIi5e41dPIPxqIG-
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

datos = []
out = widgets.Output()

def agregar_dato(b):
    if entrada.value:
        datos.append(entrada.value)
        entrada.value = ""
        actualizar_lista()
    else:
        with out:
            clear_output()
            print("Advertencia: Ingrese un dato antes de agregar.")

def limpiar_datos(b):
    datos.clear()
    actualizar_lista()

def actualizar_lista():
    with out:
        clear_output()
        for dato in datos:
            print(dato)

# Crear widgets
entrada = widgets.Text(placeholder="Ingrese un dato")
btn_agregar = widgets.Button(description="Agregar")
btn_limpiar = widgets.Button(description="Limpiar")

# Asignar funciones a los botones
btn_agregar.on_click(agregar_dato)
btn_limpiar.on_click(limpiar_datos)

# Mostrar interfaz
display(entrada, btn_agregar, btn_limpiar, out)